spon-us/SponUs-BE

- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
- #19
-  enum 필드에 대한 `@NotBlank` 어노테이션 `@NotNull`로 변경
- 🤗
> 🐛 [Bug] enum 필드에 대한 @NotBlank 어노테이션 @NotNull로 변경

- .github/workflows/gradle.yml
- src/main/resources/application-prod.yml
- resolves #36 
- S3 관련 설정 yml 및 Actions 스크립트에 추가하였습니다.
- folder 부분은 추후 도메인 별로 구분하면 좋을 것 같습니다.
- 머지 후 ci / cd 파일 분리하도록 하겠습니다~
- 정상 작동 확인 후 머지하도록 하겠습니다!
> 💚 [CI/CD] S3에 따른 yml 및 배포 스크립트 수정

- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementCreateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementCreateResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- resolves #38 
- 공고 작성 기능 개발
-
> :sparkles: [FEATURE] 공고 작성 기능 개발

- .github/workflows/cd_gradle.yml
- .github/workflows/ci_gradle.yml
- .github/workflows/gradle.yml
- resolves #44 
- ci, cd 파일 분리
- x
> 💚 [CI/CD]: ci, cd 파일 분리

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportQueryService.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
- resolves #49 
- 네이밍 변경
- controller 수정
- 화이띵 !
> :recycle: [REFACTOR] 보고서 관련 기능 수정

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/AnnouncementBriefResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementCreateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementBriefResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementCreateResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementUpdateResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- resolves #51 
- 상태별 공고 목록 조회하기
- 아자아자
> ✨ [FEATURE] 상태별 공고 조회 기능 개발

- src/main/java/com/sponus/sponusbe/auth/annotation/AuthOrganizationArgumentResolver.java
- src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
- src/main/java/com/sponus/sponusbe/global/config/SwaggerConfig.java
- resolves #57 
- 스웨거에서 토큰 삽입이 가능하도록 수정하였습니다.
- 👍
> 🐛 [BUG] Swagger 토큰 관련 버그 수정

- http/test.http
- resolves #70 
- 공고 테스트 파일 수정
- 아자아자아자자
> 🔨 test: 공고 테스트 파일 수정

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationQueryService.java
- resolves #64 
- 조직 조회 기능 개발
-
> ✨ feat: 조직 조회 기능 개발

- src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomExpiredJwtException.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomMalformedException.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomNoTokenException.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/CustomSignatureException.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/JwtAccessDeniedHandler.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/JwtAuthenticationEntryPoint.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityCustomException.java
- src/main/java/com/sponus/sponusbe/auth/jwt/exception/SecurityErrorCode.java
- src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtExceptionFilter.java
- src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
- src/main/java/com/sponus/sponusbe/global/common/exception/GlobalExceptionHandler.java
- src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
- resolves #62 
- EntryPoint 추가
- 예외 코드 정리
- 개발 편의를 위해 시큐리티 예외 세부내용을 출력하도록 변경하였습니다.
- 이제는 적당히 마무리하고 빨리 기능개발하겠습니다..
> ️♻️ refactor: 시큐리티 구조 개선

- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeImage.java
- resolves #81 
- Announcement 에서 Image 제거, Propose 에 Image 추가
- : )
> 🐛 fix: 엔티티 수정(Announcement, Propose)

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/entity/BookmarkStatus.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
- resolves #92
- 북마크 최근 저장순 조회 기능 개발
- BookmarkStatus 추가
- 화띵
> ✨ feat: 북마크 최근 저장순 조회 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
- src/main/java/com/sponus/sponusbe/domain/tag/service/TagQueryService.java
- src/main/resources/data.sql
- resolves #75 
-  태그 조회 기능 구현
-  request 테스트 진행못했습니다. 토큰 관련 이슈가 있는 것 같습니다. todo로 남겨두었습니다.
> ✨ feat: 태그 조회 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
- src/main/java/com/sponus/sponusbe/domain/tag/dto/request/TagUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/tag/entity/Tag.java
- src/main/java/com/sponus/sponusbe/domain/tag/service/TagService.java
- resolves #76 
- 태그 수정 기능 개발
-
> ✨ feat: 태그 수정 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/tag/controller/TagController.java
- src/main/java/com/sponus/sponusbe/domain/tag/service/TagService.java
- resolves #77
-  태그 삭제 기능 개발
-
> ✨ feat: 태그 삭제 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationDetailGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/request/OrganizationLinkCreateRequest.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/response/OrganizationLinkCreateResponse.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/response/OrganizationLinkGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/entity/OrganizationLink.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkException.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/repository/OrganizationLinkRepository.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkQueryService.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkService.java
- src/main/java/com/sponus/sponusbe/domain/tag/exception/TagErrorCode.java
- resolves #96
- 조직 링크 생성 기능 개발
-
> ✨ feat: 조직 링크 생성 기능 개발

- src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
- resolves #109 
- 제안 삭제 기능 (제안 id)
-
> ✨ feat: 제안 삭제 기능 구현

- .github/workflows/ci_gradle.yml
- src/main/java/com/sponus/sponusbe/global/config/EmailConfig.java
- src/main/resources/application-prod.yml
- resolves #111 
- 이메일 관련 배포 스크립트 & yml 수정
-
> 👷 ci: 이메일 관련 yml & 스크립트 수정

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/exception/OrganizationLinkErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkQueryService.java
- resolves #98
- 조직 링크 조회 기능 개발
-
> ✨ feat: 조직 링크 조회 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/dto/request/OrganizationLinkUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/entity/OrganizationLink.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkService.java
- resolves #97
- 조직 링크 수정 기능 개발
-
> ✨ feat: 조직 링크 수정 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
- src/main/java/com/sponus/sponusbe/domain/organizationLink/service/OrganizationLinkService.java
- resolves #99
- 조직 링크 삭제 기능 개발
-
>  feat: 조직 링크 삭제 기능 개발

- http/test.http
- src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
- src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/sponus/sponusbe/auth/jwt/util/JwtUtil.java
- src/main/java/com/sponus/sponusbe/global/config/SwaggerConfig.java
- resolves #85 
- 토큰 재발급 로직 분리했습니다
- 분리 작업 중에 재발급 로직 조금 수정해서, jwtUtil에도 변화 있어요
> ♻️ refactor: 토큰 재발급 로직 분리

- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementCreateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementStatus.java
- src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeDetailGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeAttachment.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeImage.java
- src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeAttachmentRepository.java
- src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeImageRepository.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
- src/main/java/com/sponus/sponusbe/global/util/MultipartJackson2HttpMessageConverter.java
- src/main/resources/application.yml
- src/main/resources/data.sql
- resolves #108 
-  제안 조회시 첨부파일 추가, 공고 상태 변경
-
> ✨ feat: 제안 조회시 첨부파일 추가, 공고 상태 변경

- http/test.http
- src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLoginFilter.java
- src/main/java/com/sponus/sponusbe/auth/jwt/filter/CustomLogoutHandler.java
- src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
- resolves #120 
- 로그인, 로그아웃 시 fcm 토큰도 처리하도록 수정했습니다.
- 다들 홧팅
> ♻️ refactor: fcm토큰 로그인/로그아웃 추가

- src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
- src/main/java/com/sponus/sponusbe/domain/report/dto/ReportAttachmentResponse.java
- src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
- src/main/java/com/sponus/sponusbe/domain/report/entity/ReportAttachment.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
- resolves #135 
- 보고서 작성 기능 첨부파일 추가
- 홧띵
> :sparkles: feat: 보고서 작성 기능 첨부파일 추가

- src/main/java/com/sponus/sponusbe/domain/report/controller/ReportController.java
- src/main/java/com/sponus/sponusbe/domain/report/dto/ReportCreateRequest.java
- src/main/java/com/sponus/sponusbe/domain/report/dto/ReportGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/report/entity/Report.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportQueryService.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
- resolves #137 
- 보고서 조회 기능 이미지, 첨부파일 추가
- 보고서 끝내겠슴다 아자아자
> ✨ feat: 보고서 조회 기능 이미지, 첨부파일 추가

- src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
- resolves #141 
- 북마크 cascade 처리
- 왕
> :recycle: refactor: 북마크 cascade 처리

- http/test.http
- out/production/resources/data.sql
- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- src/main/resources/data.sql
> ✨ feat: 공고 카테고리별 조회

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
- src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
- resolves #148 
- iOS팀에서 제보를 받아 화면설계서(0201 ver)에 맞게끔 조금 수정했습니다
- 다들 새복많받 😎
> ♻️ refactor : request dto 및 엔티티에 null 허용

- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/entity/Bookmark.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
- resolves #140 
- 북마크 조회 기능 이미지 추가
- 북마크 cascade 처리 수정
- 와 설날!
> ✨ feat: 북마크 조회 기능 이미지 추가

- src/main/java/com/sponus/sponusbe/domain/s3/S3Controller.java
- resolves #162 
- S3 TestController deleteImage 수정
-
> 🐛 fix: S3 이미지 삭제 에러 해결

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeStatusUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
- src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
- resolves #161 
- 제안을 받은 단체가 제안 열람시 상태가 VIEWED로 변경되도로 수정
- 제안 수락/거절/중단 API 분리
-
> ✨ feat: 제안 열람됨 상태 추가 & 제안 수락 기능 분리

- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- resolves #157 
- https://github.com/spon-us/SponUs-BE/issues/157
-
> ✨ feat: 실시간 인기 공고, 추천 공고 임시 구현

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/notification/exception/NotificationErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/notification/exception/NotificationException.java
- src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
- src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
- resolves #160
- 알림 삭제 기능 구현 및 임시 fcm 토큰 발급
-
> ✨feat: 알림 삭제 구현 및 임시 fcm 토큰 발급

- src/main/java/com/sponus/sponusbe/domain/notification/entity/Notification.java
- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
- resolves #167 
- 제안 보내기 알림 추가
- 알림 엔티티 불필요한 컬럼 제거
-
> :recycle: refactor: 제안 보내기 알림 추가

- src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- resolves #174 
- POST -> PATCH 변경
-
> :recycle: refactor: POST -> PATCH 변경

- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/request/AnnouncementUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementStatusUpdateResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- src/main/java/com/sponus/sponusbe/domain/announcement/entity/enums/AnnouncementStatus.java
- src/main/java/com/sponus/sponusbe/domain/announcement/exception/AnnouncementErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/request/ProposeStatusUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
- src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeService.java
- src/main/java/com/sponus/sponusbe/global/common/exception/GlobalExceptionHandler.java
- resolves #181
- 공고 상태 변경 기능 분리
- Enum 예외처리
-
> ️♻️ refactor: 공고 상태 변경 기능 분리

- src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/dto/BookmarkGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkQueryService.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkService.java
- src/main/java/com/sponus/sponusbe/domain/report/service/ReportService.java
- resolves #102 
- 북마크된 공고 목록 조회 많은 순 조회 기능 개발
- 북마크!
> ✨ feat: 북마크된 공고 목록 조회 많은 순 조회 기능 개발

- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- src/main/java/com/sponus/sponusbe/domain/bookmark/service/BookmarkQueryService.java
- resolves #180 
- 포트폴리오 페이지 : 내가 올린 공고 목록 조회 (OPENED)
- 얍....
> :sparkles: feat: 게시중 상태 내가 올린 공고 목록 조회 개발

- src/main/java/com/sponus/sponusbe/domain/announcement/controller/AnnouncementController.java
- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- resolves #190 
- 내가 올린 공고 목록 조회 기능 개발
- 내가 올린 / 게시중인 공고 목록 조회 기능 수정
- getMyAnnouncement / getMyOpenedAnnouncement 이렇게 해놓긴 했는데 더 나은 이름 추천받습니다 ....
> :sparkles: feat: 내가 올린 공고 목록 조회 기능 개발

- src/main/java/com/sponus/sponusbe/domain/announcement/repository/AnnouncementRepository.java
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementQueryService.java
- resolves #192 
- 공고 조회 기능 Status.OPENED 찾을 때 .filter로 변경
- 얍얍
> :recycle: refactor: 공고 조회 기능 Service 수정

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/announcement/service/AnnouncementService.java
- src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
- resolves #196 
- firebase 요청 헤더 변경
-
> 🐛 fix: firebase 요청 헤더 변경

- .github/workflows/ci_gradle.yml
- src/main/java/com/sponus/sponusbe/domain/notification/service/FirebaseService.java
- #198 
- 알림 에러 해결중
- request 로그 추가
-
> :bug: fix: 알림 에러 해결

- src/main/java/com/sponus/sponusbe/domain/announcement/dto/response/AnnouncementSummaryResponse.java
- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- resolves #200 
- AnnouncementSummaryResponse 북마크 횟수 추가
- 공고 목록 조회 시 북마크 횟수 확인 가능
- 얍얍
> ️♻️ refactor: response 북마크 횟수 추가

- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/response/DateGroupedProposeResponse.java
- src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeSummaryGetResponse.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
- src/main/java/com/sponus/sponusbe/domain/propose/service/ProposeQueryService.java
- resolves #202 
- 제안에 보고서 작성 상태 추가
- 날짜기준 그룹핑 + 내림차순 정렬
-
> ✨ feat: 제안에 보고서 작성상태 추가

- build.gradle
- src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentController.java
- src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentViewController.java
- src/main/java/com/sponus/sponusbe/domain/payment/dto/PaymentRequest.java
- src/main/java/com/sponus/sponusbe/global/config/SecurityConfig.java
- src/main/resources/templates/payment.html
- resolves #107 
- 임시 결제 승인 기능 구현
-
> ✨ feat: 임시 결제 승인 기능 구현

- .github/workflows/ci_gradle.yml
- out/production/resources/templates/payment.html
- src/main/resources/application-prod.yml
- resolves #205 
- 포트원 관련 배포 yml 수정
-
> 🐛 fix: 포트원 관련 배포 yml 수정

- src/main/java/com/sponus/sponusbe/domain/payment/controller/PaymentController.java
- src/main/java/com/sponus/sponusbe/domain/payment/dto/PaymentRequest.java
- src/main/java/com/sponus/sponusbe/domain/payment/service/PaymentService.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
- src/main/java/com/sponus/sponusbe/domain/propose/exception/ProposeErrorCode.java
- src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeRepository.java
- src/main/resources/templates/payment.html
- resolves #207 
- 제안 결제 성공 시 상태 변경
- 혹시 몰라서 기존 정보를 블러처리 하지는 않았음
-
> ✨ feat: 제안 결제 성공 시 상태 변경

- src/main/java/com/sponus/sponusbe/auth/jwt/filter/JwtAuthenticationFilter.java
- resolves #211 
- 토큰 만료 시 400에러 뱉도록 개선
-
> ♻️ refactor: 토큰 만료 시 응답 개선

- src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationUpdateRequest.java
- src/main/java/com/sponus/sponusbe/domain/organization/entity/Organization.java
- src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
- resolves #159.
- 조직 이미지 S3 저장 로직 추가
-
> ✨ feat: 조직 이미지 S3 저장 로직 추가

- src/main/java/com/sponus/sponusbe/domain/announcement/entity/Announcement.java
- resolves #217 
- 공고 및 제안 삭제 문제 해결
- 얍
> 🐛 fix: 공고 및 제안 삭제 문제 해결

- src/main/java/com/sponus/sponusbe/domain/propose/entity/ProposeStatus.java
- resolves #221 
- 제안 완료(협업 완료) 기능 추가
-
> ✨ feat: 제안 완료(협업 완료) 기능 추가

- src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeCustomRepository.java
- src/main/java/com/sponus/sponusbe/domain/propose/repository/ProposeCustomRepositoryImpl.java
- resolves #223 
- 내가 받은 제안 응답 형식 개선
-
> ✨ feat: 내가 받은 제안 응답 형식 개선

- out/production/resources/application-prod.yml
- out/production/resources/templates/payment.html
- src/main/java/com/sponus/sponusbe/domain/s3/S3Service.java
- resolves #227 
- S3 uploadFile 반환값 수정
-
> 🐛 fix: S3 uploadFile 반환값 수정

- src/main/java/com/sponus/sponusbe/domain/propose/dto/response/ProposeDetailGetResponse.java
> ✨ feat: 제안 상세정보에 단체 이미지 추가

- src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationJoinRequest.java
- src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationService.java
- resolves #233 
- 회원가입 시 이미지 삭제
-
> 🐛 fix: 회원가입 시 이미지 제거

- src/main/java/com/sponus/sponusbe/domain/propose/entity/Propose.java
> 🐛 fix: 제안 상태(compeleted) 관련 오류 수정

- src/main/java/com/sponus/sponusbe/domain/notification/dto/response/NotificationSummaryResponse.java
- src/main/java/com/sponus/sponusbe/domain/notification/entity/Notification.java
- src/main/java/com/sponus/sponusbe/domain/notification/repository/NotificationRepository.java
- src/main/java/com/sponus/sponusbe/domain/organization/service/OrganizationQueryService.java
- resolves #239 
- 알림 조회 최신순으로 수정
-
> ♻️ refactor: 알림 조회 최신순으로 수정

- http/test.http
- src/main/java/com/sponus/sponusbe/domain/organization/dto/OrganizationDetailGetResponse.java
- resolves #241 
- subOrganizationType null 처리
-
> 🐛 fix: subOrganizationType null 처리

- .github/workflows/ci_gradle.yml
- Dockerfile
- api/src/main/resources/application.yml
- core/core-infra-db/src/main/resources/application-db.yml
- resolves #247 
- Dockerfile 내 jar file 경로 수정
- ci 파일 수정
- application-db.yml 내 local profile 부분 수정
-
> 🐛 fix: 멀티모듈 cd 에러 해결

- .github/workflows/cd_gradle.yml
- resolves #268
- cd.yml 파이어베이스 키 설정
-
> 🐛 fix: cd.yml 수정

- core/core-infra-db/src/main/resources/application-db.yml
- resolves #274
- postgresql -> mysql 변경
- 배포 yml 수정 완
-
> ️refactor: postgresql -> mysql로 변경

- api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
- api/src/main/java/com/sponus/sponusbe/domain/bookmark/controller/BookmarkController.java
- api/src/main/java/com/sponus/sponusbe/domain/notification/controller/FirebaseTestController.java
- api/src/main/java/com/sponus/sponusbe/domain/organization/club/controller/ClubController.java
- api/src/main/java/com/sponus/sponusbe/domain/organization/company/controller/CompanyController.java
- api/src/main/java/com/sponus/sponusbe/domain/organization/controller/OrganizationController.java
- api/src/main/java/com/sponus/sponusbe/domain/organizationLink/controller/OrganizationLinkController.java
- api/src/main/java/com/sponus/sponusbe/domain/portfolio/controller/PortfolioController.java
- api/src/main/java/com/sponus/sponusbe/domain/propose/controller/ProposeController.java
- api/src/main/java/com/sponus/sponusbe/domain/s3/S3TestController.java
- api/src/main/java/com/sponus/sponusbe/global/enums/ApiPath.java
- core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
- resolves #282 
- security config path 수정했습니다!
- 추가로, API package에 있는 api path 다 const처리 했으니 머지하고 작업 이어서 해주세요!
- 아마 conflict 날 수도 있는데, 큰 수정사항 아니니 바로 이해하실 수 있으실 겁니다
- 혹시 그냥 원래대로 쓰는게 낫다고 생각하시면 의견 주세용
- 홧팅
> refactor: login 리팩토링

- http/test.http
- resolves #284 
- http.test version2로 바꿨습니다
- 별거 아니니 바로 머지할게용
> refactor: update api ver 1 -> 2

- api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
- core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/repository/OrganizationRepository.java
- core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
- resolves #286 
- authcontroller에 api 개발
- organization jpa repository에 함수 추가
- security config 일부 수정
- 리뷰 해주세용
> feat: impl duplicate email verification

- api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
- core/core-domain/src/main/java/com/sponus/coredomain/domain/organization/repository/OrganizationRepository.java
- core/core-infra-email/build.gradle
- core/core-infra-email/src/main/java/com/sponus/coreinfraemail/EmailUtil.java
- core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
- resolves #288 
- 이메일 인증코드 전송 API 개발
- redis를 통해 만료 기한 300s로 설정
- 리뷰 해주세용
> feat: Impl sending authentication code with email

- api/src/main/java/com/sponus/sponusbe/auth/controller/AuthController.java
- core/core-infra-email/src/main/java/com/sponus/coreinfraemail/EmailUtil.java
- core/core-infra-security/src/main/java/com/sponus/coreinfrasecurity/config/SecurityConfig.java
- resolves #291 
- 인증코드 검증 API 구현
- redis에서 code값 삭제
- 인증코드 전송 API path명 수정 `/email` -> `/send-code`
-
> feat: Impl code verification api
